name: clean_trust
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_spinkit: ^5.2.2
  persistent_bottom_nav_bar: ^6.2.1
  dropdown_search: ^5.0.6
  http: ^1.6.0
  shared_preferences: ^2.5.4
  geolocator: ^14.0.2
  mobile_scanner: ^7.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0
  file_picker: ^10.3.8
  intl: ^0.20.2
  url_launcher: ^6.3.2
  geocoding: ^4.0.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Outfit_Regular
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
    - family: Outfit_SemiBold
      fonts:
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
    - family: Outfit_Bold
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
    - family: Outfit_Medium
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
    - family: Outfit_Light
      fonts:
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
    - family: OpenSans_SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Lato_Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
    - family: Inter_Regular
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
    - family: Inter_Medium
      fonts:
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
    - family: Inter_Bold
      fonts:
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
    - family: Inter_SemiBold
      fonts:
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: DMSans_Medium
      fonts:
        - asset: assets/fonts/DMSans_18pt-Medium.ttf
          weight: 400

# flutter_native_splash must be outside flutter section
flutter_native_splash:
  color: "#0A2841"
  image: assets/images/splash_logo.png

  android_12:
    color: "#0A2841"
    image: assets/images/splash_logo.png

  android: true
  ios: true
